### ISSUE TITLE
Beberapa tombol dan link tidak redirect ke apapun

### ISSUE THREAD

**Issue by Neorocket64** [2018-PemrogramanWeb-D/tugas7-fp-pronlc#1]
Contohnya ini
![capture](https://user-images.githubusercontent.com/17949796/50198769-afff8800-037f-11e9-8677-5d0a508769f5.PNG)

**Comment by n0tlu5** [comment]
maaf, ini bukan bug, namun proNLC masih belum membuat akun-akun social media.
